name: Send Firebase Push Notification

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run: |
          echo "Setting up Firebase authentication"

      - name: Send Push Notification
        run: |
          curl -X POST "https://fcm.googleapis.com/v1/projects/${{ secrets.FIREBASE_PROJECT_ID }}/messages:send" \
            -H "Authorization: Bearer $(echo '${{ secrets.FIREBASE_PRIVATE_KEY }}' | base64 --decode | jq -r '.private_key')" \
            -H "Content-Type: application/json" \
            -d '{
              "message": {
                "token": "YOUR_DEVICE_FCM_TOKEN",
                "notification": {
                  "title": "Weather Alert",
                  "body": "Severe storm approaching your area!"
                },
                "android": {
                  "priority": "high"
                }
              }
            }'
