name: Send Firebase Push Notification

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Firebase Authentication
        run: |
          echo '${{ secrets.FIREBASE_CREDENTIALS }}' | base64 --decode > firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-key.json

          ACCESS_TOKEN=$(gcloud auth application-default print-access-token)
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Send Push Notification
        run: |
          curl -X POST "https://fcm.googleapis.com/v1/projects/${{ secrets.FIREBASE_PROJECT_ID }}/messages:send" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "message": {
                "token": "fDaXdgCPQQKA-MAMbu-mzo:APA91bF9oiB1MXRQrBUaR9o352p3MimxPxTzgi0MTWJXpm210j9wnbrLADtPTx_zETncB6201Q4nDXhczFaUrxh9MZX9BbMeGF5_xeThpGjDm8t_5xNgBmQ",
                "notification": {
                  "title": "Weather Alert",
                  "body": "Severe storm approaching your area!"
                },
                "android": {
                  "priority": "high"
                }
              }
            }'
